sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

php:
 - '7.2'

install:
  - travis_retry composer install $COMPOSER_ARGS --ignore-platform-reqs
  - travis_retry composer require --dev $COMPOSER_ARGS