sudo: false

language: php

services:
  - redis-server

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - COVERAGE_DEPS="php-coveralls/php-coveralls"

php:
 - '7.2'

before_install: echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - travis_retry composer install $COMPOSER_ARGS --ignore-platform-reqs
  - travis_retry composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS
  - stty cols 120 && composer show

script:
  - phpunit --colors=always --coverage-clover clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls

notifications:
  email: false