version: "3.6"
services:
  php-built-in-server:
    container_name: express-me-php
    command: php -S 0.0.0.0:80 -t ./public
    build:
      context: ./config/docker
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
#### PHP COMPOSER ####
  composer:
    container_name: php-composer
    image: composer:1.6.3
    restart: "no"
    command: install
    working_dir: /var/www
    volumes:
      - ./:/var/www
#### DATABASE ####
  postgres:
    container_name: express-me-postgres
    image: postgres:10.3-alpine
    ports:
      - "5432:5432"
    restart: always
#### DATABASE UI
  adminer:
    container_name: express-me-adminer
    image: adminer:latest
    restart: always
    ports:
      - "8090:8080"
#### REDIS ####
  redis:
    container_name: express-me-redis
    image: redis:4.0.9-alpine
    ports:
      - "6379:6379"
    restart: always
#### Mail UI ####
  mailhog:
    container_name: express-me-mailhog
    image: mailhog/mailhog:latest
    ports:
      - "8081:8025"