<?php

$this->headLink()
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css')
    ->prependStylesheet('//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css')
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css');
?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="shortcut icon" href="https://framework.zend.com/ico/favicon.ico" />
    <?php echo $this->headTitle('Personal blog')->setSeparator(' - ')->setAutoEscape(false); ?>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>
    <style>
        body { padding-top: 60px; }
        .app { min-height: 100vh; }
        .zf-green, h2 a { color: #68b604; }
        .bg-dark {background-color: #343a40;}
        .social-links a { color:white; }
    </style>
</head>
<body class="app">
    <header class="app-header">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?php echo $this->url('home'); ?>">Personal blog</a>
                </div>
            </div>
        </nav>
    </header>

    <div class="app-content">
        <main class="container">
            <?php echo $this->content; ?>
        </main>
    </div>

    <!-- Footer -->
    <footer class="footer bg-dark text-white">
        <!-- Social Icons -->
        <div class="bg-primary">
            <div class="container">
                <div class="row py-4">
                    <div class="col-md-6 col-lg-7">
                        <h4 class="mb-0 white-text">Follow me on social networks</h4>
                    </div>
                    <div class="col-md-6 col-lg-5 text-right social-links">
                        <a href="#" target="_blank"><i class="fa fa-twitter white-text mr-lg-4 fa-2x"> </i></a>
                        <a href="#" target="_blank"><i class="fa fa-google-plus white-text mr-lg-4 fa-2x"> </i></a>
                        <a href="#" target="_blank"><i class="fa fa-instagram white-text mr-lg-4 fa-2x"> </i></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Social Icons -->

        <div class="container-fluid">
            <p class="text-center m-0 py-1">
                &copy; <?php echo date('Y'); ?>
            </p>
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
</body>
</html>