<div class="container col-lg-12 main">
    <div class="col-lg-12 post">
        <div class="container">
            <h1 class="zf-green"><?php echo $post->getTitle(); ?></h1>
            <div class="body-text">
                <p class="text-muted">Myroslav Zozulia | October 7, 2018 | <?php echo $this->escapeHtml($tags); ?></p>
                <hr>
                <div class="row">
                    <div class="col-lg-12">
                        <p><?php echo $post->getContent(); ?></p>
                    </div>
                </div>
                <br/>
            </div>
        </div>
    </div>
</div>

